apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mcpcan.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-80"
data:
  env.js: |-
    {{- $isDemo := eq $.Values.global.runMode "demo" }}
    {{- $webPath := .Values.global.webPathRule }}
    {{- if eq $webPath "/" }}
      {{- $webPath = "" }}
    {{- end }}
    window.__APP_CONFIG__ = {{ dict
      "VITE_DEMO" (printf "%v" $isDemo)
      "API_BASE" .Values.global.apiPathRule
      "PUBLIC_PATH" $webPath
      | toJson }}
{{- if .Values.services.entry.enabled }}
  traefik.yaml: |-
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    entryPoints:
      web:
        address: ":80"
    providers:
      file:
        filename: "/etc/traefik/dynamic.yaml"
        watch: true
    log:
      level: "INFO"
      format: "json"
      filePath: "/dev/stdout"
    accessLog:
      format: "json"
      fields:
        headers:
          defaultMode: keep
          names:
            X-Consum-User: keep

  dynamic.yaml: |-
    http:
      middlewares:
        strip-api-prefix:
          stripPrefix:
            prefixes:
              - "{{ .Values.global.apiPathRule }}"
        strip-web-prefix:
          stripPrefix:
            prefixes:
              - "{{ .Values.global.webPathRule }}"
        external-auth:
          forwardAuth:
            address: "http://{{ .Values.services.authz.service.name }}:{{ .Values.services.authz.service.port }}/authz/validate"
            trustForwardHeader: true
            authResponseHeaders: ["X-Consum-User-Id", "X-Custom-User-Info", "X-Trace-Id"]
      serversTransports:
        https-skip-verify-transport:
          insecureSkipVerify: true
      routers:
        authz-public:
          rule: "PathPrefix(`{{ .Values.global.apiPathRule }}/authz/login`) || PathPrefix(`{{ .Values.global.apiPathRule }}/authz/logout`) || PathPrefix(`{{ .Values.global.apiPathRule }}/authz/register`) || PathPrefix(`{{ .Values.global.apiPathRule }}/authz/refresh`) || PathPrefix(`{{ .Values.global.apiPathRule }}/authz/validate`) || PathPrefix(`{{ .Values.global.apiPathRule }}/authz/encryption-key`) || PathPrefix(`/health`) || PathPrefix(`{{ .Values.global.apiPathRule }}/health`)"
          service: "authz-service"
          entryPoints: ["web"]
          middlewares:
            - "strip-api-prefix"
          priority: 100
        market-pulic:
          rule: "PathPrefix(`{{ .Values.global.apiPathRule }}/market/code/download`) || PathPrefix(`{{ .Values.global.apiPathRule }}/market/openapi/download`)"
          service: "market-service"
          entryPoints: ["web"]
          middlewares:
            - "strip-api-prefix"
          priority: 100
        authz-protected:
          rule: "PathPrefix(`{{ .Values.global.apiPathRule }}/authz`)"
          service: "authz-service"
          entryPoints: ["web"]
          middlewares:
            - "strip-api-prefix"
            - "external-auth"
        market-router:
          rule: "PathPrefix(`{{ .Values.global.apiPathRule }}/market`)"
          service: "market-service"
          entryPoints: ["web"]
          middlewares:
            - "strip-api-prefix"
            - "external-auth"
        mcp-gateway:
          rule: "PathPrefix(`/mcp-gateway`)"
          service: "market-service"
          entryPoints: ["web"]
          middlewares: []
          priority: 1000
        web-router:
          rule: "PathPrefix(`{{ .Values.global.webPathRule }}`)"
          service: "web-service"
          entryPoints: ["web"]
          middlewares:
            - "strip-web-prefix"
          priority: 1
      services:
        authz-service:
          loadBalancer:
            servers:
              - url: "http://{{ .Values.services.authz.service.name }}:{{ .Values.services.authz.service.port }}"
        market-service:
          loadBalancer:
            servers:
              - url: "http://{{ .Values.services.market.service.name }}:{{ .Values.services.market.service.port }}"
        web-service:
          loadBalancer:
            servers:
              - url: "http://{{ .Values.services.web.service.name }}:{{ .Values.services.web.service.port }}"
{{- end }}
{{- if .Values.services.authz.enabled }}
  authz.yaml: |-
    runMode: {{ .Values.global.runMode }}
    server:
      serviceName: {{ .Values.services.authz.name | default "mcp-authz" }}
      httpPort: {{ .Values.services.authz.service.port }}
    secret: {{ .Values.global.appSecret }}
    database:
      mysql:
        host: {{ .Values.infrastructure.mysql.service.name }}
        port: {{ .Values.infrastructure.mysql.service.port }}
        database: {{ .Values.infrastructure.mysql.auth.database }}
        username: {{ .Values.infrastructure.mysql.auth.username }}
        password: {{ .Values.infrastructure.mysql.auth.password }}
      redis:
        host: {{ .Values.infrastructure.redis.service.name }}
        port: {{ .Values.infrastructure.redis.service.port }}
        password: {{ .Values.infrastructure.redis.auth.password }}
        db: {{ .Values.infrastructure.redis.auth.db }}
    log:
      level: debug
      format: json
    storage:
      rootPath: {{ .Values.global.mountStorage.rootPath }}
      codePath: {{ .Values.global.mountStorage.codePackagePath }}
      staticPath: {{ .Values.global.mountStorage.staticPath }}
{{- end }}
{{- if .Values.services.market.enabled }}
  market.yaml: |-
    runMode: {{ .Values.global.runMode }}
    server:
      serviceName: {{ .Values.services.market.name | default "mcp-market" }}
      httpPort: {{ .Values.services.market.service.port }}
    secret: {{ .Values.global.appSecret }}
    runEnvironment:
      enabled: true
      name: "Default-Run-Environment"
      type: "kubernetes"
      kubernetes:
        namespace: {{ .Release.Namespace }}
        configPath: "/etc/kube/kubeconfig.yaml"
    services:
      mcpMarket:
        host: {{ .Values.services.market.name | default "mcp-market" }}-svc
        port: {{ .Values.services.market.service.port }}
      mcpAuthz:
        host: {{ .Values.services.authz.name | default "mcp-authz" }}-svc
        port: {{ .Values.services.authz.service.port }}
    database:
      mysql:
        host: {{ .Values.infrastructure.mysql.service.name }}
        port: {{ .Values.infrastructure.mysql.service.port }}
        database: {{ .Values.infrastructure.mysql.auth.database }}
        username: {{ .Values.infrastructure.mysql.auth.username }}
        password: {{ .Values.infrastructure.mysql.auth.password }}
      redis:
        host: {{ .Values.infrastructure.redis.service.name }}
        port: {{ .Values.infrastructure.redis.service.port }}
        password: {{ .Values.infrastructure.redis.auth.password }}
    log:
      level: debug
      format: json
    code:
      upload:
        maxFileSize: {{ .Values.global.codeUploadMaxFileSize }}
        allowedExtensions: [".zip", ".tar.gz", ".tar", ".dxt", ".mcpb"]
    storage:
      rootPath: {{ .Values.global.mountStorage.rootPath }}
      codePath: {{ .Values.global.mountStorage.codePackagePath }}
      staticPath: {{ .Values.global.mountStorage.staticPath }}
      openapiFilePath: {{ .Values.global.mountStorage.openapiFilePath }}
    init:
      admin_username: {{ .Values.services.init.loginUser.username }}
      admin_password: {{ .Values.services.init.loginUser.password }}
      admin_nickname: admin
      admin_role_name: admin
      admin_role_description: admin role
      admin_role_level: 1
      admin_data_scope: all
{{- end }}
