{{- if and .Values.ingress.tls.createSecret .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName | default (printf "%s-secret" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "mcpcan.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1200"
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
{{- end }}

{{- if .Values.global.registryAuth.createSecret }}
{{- $server := .Values.global.registryAuth.server | default "ccr.ccs.tencentyun.com" -}}
{{- $username := .Values.global.registryAuth.username | required "global.registryAuth.username is required" -}}
{{- $password := .Values.global.registryAuth.password | required "global.registryAuth.password is required" -}}
{{- $auth := printf "%s:%s" $username $password | b64enc -}}
{{- $dockerconfig := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"none\",\"auth\":\"%s\"}}}" $server $username $password $auth | b64enc -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.registryAuth.secretName | default "mcpcan-registry-auth" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "mcpcan.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1100"
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfig }}
{{- end }}
