runMode: ${RUN_MODE}
server:
  serviceName: ${MCP_MARKET_SERVICE_NAME}
  httpPort: ${MCP_MARKET_SERVICE_PORT}
secret: ${APP_SECRET}
runEnvironment:
  enabled: true
  name: "Default-Run-Environment"
  type: "docker"
  docker:
    host: "unix:///var/run/docker.sock"
    network: "docker-compose_mcpcan-network"
database:
  mysql:
    host: ${MYSQL_HOST}
    port: ${MYSQL_PORT}
    database: ${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
log:
  level: debug
  format: json
code:
  upload:
    maxFileSize: ${MAX_FILE_SIZE}
    allowedExtensions: ${ALLOWED_EXTENSIONS}
storage:
  rootPath: /data/mcpcan
  codePath: /data/mcpcan/code-package
  staticPath: /data/mcpcan/static
  openapiFilePath: /data/mcpcan/openapi-file
init:
  admin_username: ${ADMIN_USERNAME}
  admin_password: ${ADMIN_PASSWORD}
  admin_nickname: ${ADMIN_NICKNAME}
  admin_role_name: ${ADMIN_ROLE_NAME}
  admin_role_description: ${ADMIN_ROLE_DESCRIPTION}
  admin_role_level: ${ADMIN_ROLE_LEVEL}
  admin_data_scope: ${ADMIN_DATA_SCOPE}
