
@contentType = application/json
@openapiFileID = 3d83744a-61da-4223-9fc6-25dace920b96
@chooseOpenapiFileID = eadef26c-ef6f-4024-b01d-b3d90ea4b2f1

### 创建 openapi 格式的实例
POST {{baseUrl}}/{{routerPrefix}}/instance/openapi/create
Content-Type: application/json
Authorization: {{token}}

{
  "instanceId": "",
  "name": "gordon_test",
  "notes": "",
  "iconPath": "",
  "environmentId": 1,
  "openapiFileID": "{{openapiFileID}}",
  "chooseOpenapiFileID": "{{chooseOpenapiFileID}}",
  "openapiBaseUrl": "https://mcp-dev.itqm.com/api/market",
  "sourceType": 4,
  "tokens": [
    {
      "enabledTransport": false,
      "expireAt": "",
      "headers": [

      ],
      "publishAt": 1763521401712,
      "token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjE3NjM3MTI4OTYsImlhdCI6MTc2MzYyNjQ5Nn0.h1wGp5AdwrfhRRJNNFdsSFO-8siFQaP_O20-goCIPME",
      "tokenType": 1,
      "usage": [
        "default"
      ]
    }
  ]
}
### 删除节点
DELETE {{baseUrl}}/{{routerPrefix}}/instance/34bd978a-1fd7-4875-a52a-452287377087
Content-Type: application/json
Authorization: {{token}}

### 节点列表
POST {{baseUrl}}/{{routerPrefix}}/instance/list
Content-Type: application/json
Authorization: {{token}}


### list tools
POST {{baseUrl}}/{{routerPrefix}}/instance/list-tools
Content-Type: application/json
Authorization: {{token}}

{
  "instanceID": "6b4a8b52-c7c6-4f9a-9423-af6eb928216b",
  "domain": "https://mcp-dev.itqm.com/"
}

### call tools
POST {{baseUrl}}/{{routerPrefix}}/instance/call-tools
Content-Type: application/json
Authorization: {{token}}

{
  "instanceID": "6b4a8b52-c7c6-4f9a-9423-af6eb928216b",
  "domain": "https://mcp-dev.itqm.com/",
  "toolName": "CodeService_DeleteCodePackage",
  "arguments": "{\"packageId\": \"1\"}"
}

