### 1. 创建同步到dify任务
POST {{baseUrl}}/{{routerPrefix}}/mcp_to_intelligent_task
Content-Type: application/json
Authorization: {{token}}

{
  "desc": "同步到dify",
  "domain": "https://mcp-dev.itqm.com",
  "intelligentAccessID": 2,
  "insertIntelligentInfos": [
    {
      "difyUserID": "967ecbcd-36c0-4996-8cd2-0ad35824fe9c",
      "difySpaceID": "0367fd04-7744-44f4-af74-72bb1242d898",
      "difyUserName": "kakj",
      "difySpaceName": "kakj's Workspace",
      "headers": {
        "4a10d139-56d3-417f-918e-9a1827eec30f": {
          "Token": "Bearer ZGExN2ZmNWYtOTMwNC00YTZhLTg2ZjgtZmQ2ZjA4MWFhNzkyeyJleHBpcmVBdCI6MTc2NDY3MDg5NzIwNywidXNlcklkIjoxLCJ1c2VybmFtZSI6ImFkbWluIn0=",
          "Headers": {
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjE3NjQ3NTEzMjcsImlhdCI6MTc2NDY2NDkyN30.eWUixcKcHZA8YI40vJP1tTcsmkauUMOuog7JGMla3c8"
          }
        }
      }
    }
  ],
  "mcpInstanceIDs": [
    "4a10d139-56d3-417f-918e-9a1827eec30f"
  ]
}

### 2. 查询同步到dify任务列表
GET {{baseUrl}}/{{routerPrefix}}/mcp_to_intelligent_task/list
Authorization: {{token}}

### 3. 查询同步到dify任务详情
GET {{baseUrl}}/{{routerPrefix}}/mcp_to_intelligent_task/1
Authorization: {{token}}

### 4. 取消同步到dify任务
POST {{baseUrl}}/{{routerPrefix}}/mcp_to_intelligent_task/1/cancel
Authorization: {{token}}


### 1. 创建同步到coze任务
POST {{baseUrl}}/{{routerPrefix}}/mcp_to_intelligent_task
Content-Type: application/json
Authorization: {{token}}

{
  "desc": "同步到coze",
  "domain": "https://mcp-dev.itqm.com",
  "intelligentAccessID": 4,
  "insertIntelligentInfos": [
    {
      "userID": "1308862529673482",
      "spaceID": "7581394874642595892",
      "userName": "myself",
      "spaceName": "test",
      "headers": {
        "d5744f35-260f-4808-918c-b602ac9793a1": {
          "token": "Bearer ODViMjM1MjMtZGI4MC00MzVkLWE3NzEtNzcxYzE4ZGE4YTMzeyJleHBpcmVBdCI6MTc2NjAzOTEwNjAyMiwidXNlcklkIjoxLCJ1c2VybmFtZSI6ImFkbWluIn0=",
          "Headers": {
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjE3NjYwNDY2MDYsImlhdCI6MTc2NTk2MDIwNn0.BKJ4ae8FdbvZ95WYBxP8yIjEhN3J4tCPvM-VWcE6h74"
          }
        }
      }
    }
  ],
  "mcpInstanceIDs": [
    "d5744f35-260f-4808-918c-b602ac9793a1"
  ],
  "cookie": ""
}

### 1. 创建同步到n8n任务
POST {{baseUrl}}/{{routerPrefix}}/mcp_to_intelligent_task
Content-Type: application/json
Authorization: {{token}}

{
  "desc": "同步到n8n",
  "domain": "https://mcp-dev.itqm.com",
  "intelligentAccessID": 8,
  "insertIntelligentInfos": [
    {
      "userID": "XtyKeNFWGOkGxGtR",
      "spaceID": "XtyKeNFWGOkGxGtR",
      "userName": "kakj kakj <kakjzzw@gmail.com>",
      "spaceName": "kakj kakj <kakjzzw@gmail.com>",
      "headers": {
        "3696c011-1085-407f-893c-1b46449fb50e": {
          "token": "Bearer NWUyZGNhZjEtYTJhMy00MjBlLThmYzctZWYwZDA2ODRlNTQweyJleHBpcmVfYXQiOiIxNzY3MDgzNjE2MDAwIiwidXNlcl9pZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluIn0=",
          "headers": {
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjE3NjYxMzM2MjgsImlhdCI6MTc2NjA0NzIyOH0.VoUCdkGd8kZ0pwzbvOSxf3UbIvR6BA-nSzh8buESGQc"
          }
        }
      }
    }
  ],
  "mcpInstanceIDs": [
    "3696c011-1085-407f-893c-1b46449fb50e"
  ]
}