# Runtime stage
FROM alpine:3.22

# Set apk aliyun mirror
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

# Install necessary runtime dependencies
RUN apk add --no-cache ca-certificates tzdata

# Set timezone
ENV TZ=Asia/Shanghai

RUN mkdir -p /app /app/config

# Set working directory
WORKDIR /app

# Copy binary from build stage
COPY ../backend/bin/gateway /app/gateway

# Run the application
CMD ["/app/gateway"]