package models

// GoogleProvider Google AI 提供商信息
var GoogleProvider = ProviderInfo{
	ID:          "google",
	Name:        "Google AI",
	BaseURL:     "https://generativelanguage.googleapis.com/v1beta",
	RegisterURL: "https://aistudio.google.com/app/apikey",
	DocsURL:     "https://ai.google.dev/docs",
	Models: []ModelInfo{
		// Gemini 3 Series (Preview - dev-docs 指定)
		{
			ID:              "gemini-3.1-pro-preview",
			Name:            "Gemini 3.1 Pro Preview",
			Description:     "Gemini 3.1 Pro 预览版，最新旗舰多模态模型",
			ContextLength:   1048576,
			Modality:        "text+image+video->text",
			Provider:        "google",
			SupportThinking: true,
			SupportTools:    true,
		},
		{
			ID:              "gemini-3-pro-preview",
			Name:            "Gemini 3 Pro Preview",
			Description:     "Gemini 3 Pro 预览版",
			ContextLength:   1048576,
			Modality:        "text+image+video->text",
			Provider:        "google",
			SupportThinking: true,
			SupportTools:    true,
		},
		{
			ID:           "gemini-3-flash-preview",
			Name:         "Gemini 3 Flash Preview",
			Description:  "Gemini 3 Flash 高速预览版",
			ContextLength: 1048576,
			Modality:     "text+image+video->text",
			Provider:     "google",
			SupportTools: true,
		},
		// Gemini 2.5 Series (当前主力)
		{
			ID:            "gemini-2.5-pro",
			Name:          "Gemini 2.5 Pro",
			Description:   "Gemini 2.5 Pro 高智能版",
			ContextLength: 1048576,
			Modality:      "text+image+video->text",
			Provider:      "google",
			SupportTools:  true,
		},
		{
			ID:            "gemini-2.5-pro-preview-05-06",
			Name:          "Gemini 2.5 Pro Preview",
			Description:   "Gemini 2.5 Pro 最新 Preview (2025-05)",
			ContextLength: 1048576,
			Modality:      "text+image+video->text",
			Provider:      "google",
			SupportTools:  true,
		},
		{
			ID:            "gemini-2.5-flash",
			Name:          "Gemini 2.5 Flash",
			Description:   "Gemini 2.5 Flash 高速版",
			ContextLength: 1048576,
			Modality:      "text+image+video->text",
			Provider:      "google",
			SupportTools:  true,
		},
		// Gemini 2.0 Series
		{
			ID:            "gemini-2.0-flash",
			Name:          "Gemini 2.0 Flash",
			Description:   "Gemini 2.0 Flash 多模态交互",
			ContextLength: 1048576,
			Modality:      "text+image->text",
			Provider:      "google",
			SupportTools:  true,
		},
		{
			ID:              "gemini-2.0-flash-thinking-exp-1219",
			Name:            "Gemini 2.0 Flash Thinking",
			Description:     "Gemini 2.0 思考实验模型",
			ContextLength:   32768,
			Modality:        "text+image->text",
			Provider:        "google",
			SupportThinking: true,
			SupportTools:    false,
		},
		// Gemini 1.5 Series (Stable)
		{
			ID:            "gemini-1.5-pro-002",
			Name:          "Gemini 1.5 Pro-002",
			Description:   "Gemini 1.5 Pro 最新稳定版",
			ContextLength: 2000000,
			Modality:      "text+image->text",
			Provider:      "google",
			SupportTools:  true,
		},
		{
			ID:            "gemini-1.5-flash-002",
			Name:          "Gemini 1.5 Flash-002",
			Description:   "Gemini 1.5 Flash 最新稳定版",
			ContextLength: 1000000,
			Modality:      "text+image->text",
			Provider:      "google",
			SupportTools:  true,
		},
		{
			ID:            "gemini-1.5-pro",
			Name:          "Gemini 1.5 Pro",
			Description:   "Gemini 1.5 Pro 经典版",
			ContextLength: 1000000,
			Modality:      "text+image->text",
			Provider:      "google",
			SupportTools:  true,
		},
		{
			ID:            "gemini-1.5-flash",
			Name:          "Gemini 1.5 Flash",
			Description:   "Gemini 1.5 Flash 经典版",
			ContextLength: 1000000,
			Modality:      "text+image->text",
			Provider:      "google",
			SupportTools:  true,
		},
	},
}

// GoogleModels Google 模型 ID 列表
var GoogleModels = GoogleProvider.GetModelIDs()
