runMode: prod
server:
  serviceName: mcp-market
  httpPort: 8080
secret: MrKuvLNn0hc1kHRbA6EqjSPj1ecrbPDE
runEnvironment:
  enabled: true
  name: "Default-Run-Environment"
  type: "docker"
  docker:
    host: "unix:///var/run/docker.sock"
    network: "docker-compose_mcpcan-network"
database:
  mysql:
    host: mysql
    port: 3306
    database: mcpcan
    username: mcpcan-user
    password: a6ApqYJIycJJjl
  redis:
    host: redis
    port: 6379
    password: dHaARm88OXXN6e
log:
  level: info
  format: json
code:
  upload:
    maxFileSize: 100
    allowedExtensions: .zip,.tar.gz,.tar,.dxt,.mcpb
storage:
  rootPath: /data/mcpcan
  codePath: /data/mcpcan/code-package
  staticPath: /data/mcpcan/static
  openapiFilePath: /data/mcpcan/openapi-file
init:
  admin_username: admin
  admin_password: admin123
  admin_nickname: admin
  admin_role_name: admin
  admin_role_description: admin-role
  admin_role_level: 1
  admin_data_scope: all
