CREATE DATABASE IF NOT EXISTS mcpcan DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'mcpcan-user'@'%' IDENTIFIED BY 'a6ApqYJIycJJjl';
GRANT ALL PRIVILEGES ON mcpcan.* TO 'mcpcan-user'@'%';
FLUSH PRIVILEGES;