global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: docker-compose_mcpcan-network
    allowEmptyServices: true

log:
  level: "INFO"
  format: "json"
  filePath: "/dev/stdout"

accessLog:
  format: "json"
  fields:
    headers:
      defaultMode: keep
      names:
        X-Consum-User: keep
