package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"
)

const outputTemplate = `// Code generated by gen_models.go; DO NOT EDIT.
package service

import (
	openai "github.com/sashabaranov/go-openai"
)

// SupportedOpenAIModels is a list of models supported by the go-openai library.
var SupportedOpenAIModels = []string{
{{- range .Models }}
	openai.{{ . }},
{{- end }}
}
`

func main() {
	// 1. Get go-openai path
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/sashabaranov/go-openai")
	output, err := cmd.Output()
	if err != nil {
		panic(fmt.Sprintf("failed to get go-openai path: %v", err))
	}
	pkgPath := strings.TrimSpace(string(output))
	completionFile := filepath.Join(pkgPath, "completion.go")

	// 2. Parse completion.go
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, completionFile, nil, parser.ParseComments)
	if err != nil {
		panic(fmt.Sprintf("failed to parse completion.go: %v", err))
	}

	var models []string

	// 3. Extract constants
	ast.Inspect(node, func(n ast.Node) bool {
		genDecl, ok := n.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			return true
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			for _, name := range valueSpec.Names {
				// Filter for GPT and O1 models
				if strings.HasPrefix(name.Name, "GPT") || strings.HasPrefix(name.Name, "O1") || strings.HasPrefix(name.Name, "O3") || strings.HasPrefix(name.Name, "O4") {
					// Check if it's deprecated
					// The doc comment is usually on the GenDecl if it's a block, or on the Spec.
					// We check both.
					isDeprecated := false
					if genDecl.Doc != nil && strings.Contains(genDecl.Doc.Text(), "Deprecated") {
						isDeprecated = true
					}
					if valueSpec.Doc != nil && strings.Contains(valueSpec.Doc.Text(), "Deprecated") {
						isDeprecated = true
					}
					// Also check comment group associated with the spec (line comment)
					if valueSpec.Comment != nil && strings.Contains(valueSpec.Comment.Text(), "Deprecated") {
						isDeprecated = true
					}

					if !isDeprecated {
						models = append(models, name.Name)
					}
				}
			}
		}
		return true
	})

	// 4. Generate output
	// Use runtime.Caller to determine the directory of this source file
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		panic("failed to get current file path")
	}
	currentDir := filepath.Dir(filename)
	// Output directory relative to this file: ../../../internal/market/service
	outputDir := filepath.Join(currentDir, "../../../internal/market/service")
	
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		panic(err)
	}

	outputFile := filepath.Join(outputDir, "openai_models_gen.go")
	tmpl, err := template.New("models").Parse(outputTemplate)
	if err != nil {
		panic(err)
	}

	f, err := os.Create(outputFile)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, map[string]interface{}{
		"Models": models,
	}); err != nil {
		panic(err)
	}
	
	fmt.Printf("Generated openai_models_gen.go with %d models\n", len(models))
}
