root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # 监听 mcp-authz 服务的编译
  cmd = "go build -gcflags='all=-N -l' -ldflags=\"-X 'github.com/kymo-mcp/mcpcan/pkg/version.CodeMode=${CODE_MODE}'\" -o ./tmp/authz ./cmd/authz/main.go"
  bin = "./tmp/authz"
  # 使用 dlv 启动调试服务
  full_bin = "dlv --headless --listen=:2346 --api-version=2 --accept-multiclient exec ./tmp/authz --continue"
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "toml"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  delay = 1000
  stop_on_error = true
  log = "air-authz.log"

[log]
  time = true

[color]
  main = "green"
  watcher = "cyan"
  build = "yellow"
  runner = "magenta"

[misc]
  clean_on_exit = true
